version: "3.3"

services:
  stardew:
    build: docker
    container_name: stardew
    environment:
      - "DISPLAY_HEIGHT=800"
      - "DISPLAY_WIDTH=1280"
      - "SERVER_ID=docker-test"
      - "BACKUP_GCS_BUCKET=junimo-test-backups"
      - "GOOGLE_APPLICATION_CREDENTIALS=/etc/gcp/stardew-sa.json"
      - "NO_BACKEND=true"

    cpus: 0.175
    mem_limit: 1Gi

    ports:
      # # VNC
      # - 5902:5900
      # NOVNC WEB
      - 8090:5800
      # Game
      - 24643:24642/udp
      - 8082:8081
      - 8083:8080

    volumes:
      # - ./data/mods:/data/Stardew/Stardew Valley/Mods
      - ./data:/config/xdg/config/StardewValley
      - ./stardew-sa.json:/etc/gcp/stardew-sa.json
