// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: junimohost/game_manager/game_manager.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace JunimoServer.GRPC {

  /// <summary>Holder for reflection information generated from junimohost/game_manager/game_manager.proto</summary>
  public static partial class GameManagerReflection {

    #region Descriptor
    /// <summary>File descriptor for junimohost/game_manager/game_manager.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GameManagerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CipqdW5pbW9ob3N0L2dhbWVfbWFuYWdlci9nYW1lX21hbmFnZXIucHJvdG8S",
            "Gmp1bmltb2hvc3QuZ2FtZV9tYW5hZ2VyLnYxGhxnb29nbGUvYXBpL2Fubm90",
            "YXRpb25zLnByb3RvGhtnb29nbGUvcHJvdG9idWYvZW1wdHkucHJvdG8aIGdv",
            "b2dsZS9wcm90b2J1Zi9maWVsZF9tYXNrLnByb3RvIskBChFDcmVhdGVHYW1l",
            "UmVxdWVzdBIdCgp3aGljaF9mYXJtGAEgASgFUgl3aGljaEZhcm0SMAoUdXNl",
            "X3NlcGVyYXRlX3dhbGxldHMYAiABKAhSEnVzZVNlcGVyYXRlV2FsbGV0cxIn",
            "Cg9zdGFydGluZ19jYWJpbnMYAyABKAVSDnN0YXJ0aW5nQ2FiaW5zEh0KCmNh",
            "dF9wZXJzb24YBCABKAhSCWNhdFBlcnNvbhIbCglmYXJtX25hbWUYBSABKAlS",
            "CGZhcm1OYW1lMnwKEkdhbWVNYW5hZ2VyU2VydmljZRJmCgpDcmVhdGVHYW1l",
            "Ei0uanVuaW1vaG9zdC5nYW1lX21hbmFnZXIudjEuQ3JlYXRlR2FtZVJlcXVl",
            "c3QaFi5nb29nbGUucHJvdG9idWYuRW1wdHkiEYLT5JMCCyIJL3YxL2dhbWVz",
            "QlhaQmdpdGh1Yi5jb20vanVuaW1vaG9zdC9qdW5pbW8tYXBpL2dlbi9nby9q",
            "dW5pbW9ob3N0L2dhbWUtbWFuYWdlci92MaoCEUp1bmltb1NlcnZlci5HUlBD",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Api.AnnotationsReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.EmptyReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.FieldMaskReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::JunimoServer.GRPC.CreateGameRequest), global::JunimoServer.GRPC.CreateGameRequest.Parser, new[]{ "WhichFarm", "UseSeperateWallets", "StartingCabins", "CatPerson", "FarmName" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class CreateGameRequest : pb::IMessage<CreateGameRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreateGameRequest> _parser = new pb::MessageParser<CreateGameRequest>(() => new CreateGameRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<CreateGameRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::JunimoServer.GRPC.GameManagerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateGameRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateGameRequest(CreateGameRequest other) : this() {
      whichFarm_ = other.whichFarm_;
      useSeperateWallets_ = other.useSeperateWallets_;
      startingCabins_ = other.startingCabins_;
      catPerson_ = other.catPerson_;
      farmName_ = other.farmName_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public CreateGameRequest Clone() {
      return new CreateGameRequest(this);
    }

    /// <summary>Field number for the "which_farm" field.</summary>
    public const int WhichFarmFieldNumber = 1;
    private int whichFarm_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int WhichFarm {
      get { return whichFarm_; }
      set {
        whichFarm_ = value;
      }
    }

    /// <summary>Field number for the "use_seperate_wallets" field.</summary>
    public const int UseSeperateWalletsFieldNumber = 2;
    private bool useSeperateWallets_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool UseSeperateWallets {
      get { return useSeperateWallets_; }
      set {
        useSeperateWallets_ = value;
      }
    }

    /// <summary>Field number for the "starting_cabins" field.</summary>
    public const int StartingCabinsFieldNumber = 3;
    private int startingCabins_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int StartingCabins {
      get { return startingCabins_; }
      set {
        startingCabins_ = value;
      }
    }

    /// <summary>Field number for the "cat_person" field.</summary>
    public const int CatPersonFieldNumber = 4;
    private bool catPerson_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool CatPerson {
      get { return catPerson_; }
      set {
        catPerson_ = value;
      }
    }

    /// <summary>Field number for the "farm_name" field.</summary>
    public const int FarmNameFieldNumber = 5;
    private string farmName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string FarmName {
      get { return farmName_; }
      set {
        farmName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as CreateGameRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(CreateGameRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (WhichFarm != other.WhichFarm) return false;
      if (UseSeperateWallets != other.UseSeperateWallets) return false;
      if (StartingCabins != other.StartingCabins) return false;
      if (CatPerson != other.CatPerson) return false;
      if (FarmName != other.FarmName) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (WhichFarm != 0) hash ^= WhichFarm.GetHashCode();
      if (UseSeperateWallets != false) hash ^= UseSeperateWallets.GetHashCode();
      if (StartingCabins != 0) hash ^= StartingCabins.GetHashCode();
      if (CatPerson != false) hash ^= CatPerson.GetHashCode();
      if (FarmName.Length != 0) hash ^= FarmName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (WhichFarm != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WhichFarm);
      }
      if (UseSeperateWallets != false) {
        output.WriteRawTag(16);
        output.WriteBool(UseSeperateWallets);
      }
      if (StartingCabins != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(StartingCabins);
      }
      if (CatPerson != false) {
        output.WriteRawTag(32);
        output.WriteBool(CatPerson);
      }
      if (FarmName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FarmName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (WhichFarm != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(WhichFarm);
      }
      if (UseSeperateWallets != false) {
        output.WriteRawTag(16);
        output.WriteBool(UseSeperateWallets);
      }
      if (StartingCabins != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(StartingCabins);
      }
      if (CatPerson != false) {
        output.WriteRawTag(32);
        output.WriteBool(CatPerson);
      }
      if (FarmName.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(FarmName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (WhichFarm != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(WhichFarm);
      }
      if (UseSeperateWallets != false) {
        size += 1 + 1;
      }
      if (StartingCabins != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(StartingCabins);
      }
      if (CatPerson != false) {
        size += 1 + 1;
      }
      if (FarmName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FarmName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(CreateGameRequest other) {
      if (other == null) {
        return;
      }
      if (other.WhichFarm != 0) {
        WhichFarm = other.WhichFarm;
      }
      if (other.UseSeperateWallets != false) {
        UseSeperateWallets = other.UseSeperateWallets;
      }
      if (other.StartingCabins != 0) {
        StartingCabins = other.StartingCabins;
      }
      if (other.CatPerson != false) {
        CatPerson = other.CatPerson;
      }
      if (other.FarmName.Length != 0) {
        FarmName = other.FarmName;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            WhichFarm = input.ReadInt32();
            break;
          }
          case 16: {
            UseSeperateWallets = input.ReadBool();
            break;
          }
          case 24: {
            StartingCabins = input.ReadInt32();
            break;
          }
          case 32: {
            CatPerson = input.ReadBool();
            break;
          }
          case 42: {
            FarmName = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            WhichFarm = input.ReadInt32();
            break;
          }
          case 16: {
            UseSeperateWallets = input.ReadBool();
            break;
          }
          case 24: {
            StartingCabins = input.ReadInt32();
            break;
          }
          case 32: {
            CatPerson = input.ReadBool();
            break;
          }
          case 42: {
            FarmName = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
