apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: stardew-test
spec:
  type: NodePort
  ports:
    - port: 24642
      targetPort: 24642
      nodePort: 30001
      name: udp
      protocol: UDP
    - port: 8081
      targetPort: 8081
      nodePort: 30002
      name: http
      protocol: TCP
  selector:
    app: stardew-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stardew-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: stardew-test
  template:
    metadata:
      labels:
        app: stardew-test
    spec:
      containers:
        - name: stardew-test
          image: gcr.io/junimo-host/stardew-base:v0.4.1
          ports:
            - containerPort: 24642
            - containerPort: 8081
          resources:
            requests:
              cpu: "125m"
              memory: "400Mi"
            limits:
              cpu: "250m"
              memory: "512Mi"
