on: [push]

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}

jobs:
  setup-build-publish:
    name: Setup, Build, Publish
    runs-on: [buildjet-2vcpu-ubuntu-2204, buildjet-4vcpu-ubuntu-2204, buildjet-8vcpu-ubuntu-2204, buildjet-16vcpu-ubuntu-2204]

    steps:
      - name: Download Code
        uses: actions/checkout@v3

      - name: Download Stardew
        uses: wei/wget@v1
        with:
          args: -O stardew.tar.gz https://storage.googleapis.com/junimo-public/SV156.tar.gz

      - name: Decompress Stardew
        run: |-
          tar -zxf stardew.tar.gz

      - name: Download SMAPI 3.16.2
        uses: wei/wget@v1
        with:
          args: -O smapi.zip https://github.com/Pathoschild/SMAPI/releases/download/3.16.2/SMAPI-3.16.2-installer.zip

      - name: Install SMAPI
        run: |-
          unzip -qq smapi.zip -d ./smapi
          echo -e "2\n\n" | ./smapi/SMAPI\ 3.16.2\ installer/internal/linux/SMAPI.Installer --install --game-path "/home/runner/actions-runner/_work/junimohost-stardew-server/junimohost-stardew-server/Stardew Valley"
        continue-on-error: true # runs installer twice for some reason, fails on second time, but succeeds on first

      - uses: actions/setup-go@v3
        with:
          go-version: "^1.19"
          cache: true
          cache-dependency-path: daemon/go.sum

      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: "6.0.302"

      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          project_id: ${{ secrets.GKE_PROJECT }}

      - run: |-
          gcloud --quiet auth configure-docker

      - name: Docker layer cache
        uses: satackey/action-docker-layer-caching@v0.0.11
          # Ignore the failure of a step and avoid terminating the job.
        continue-on-error: true

      - name: Build and Publish
        run: |-
          make push
